#!/bin/sh

DIR=/usr/local/rpmdemo/

PROG=$DIR/bin/hello
CFG=$DIR/conf/cfg.json
LOGS=$DIR/logs/hello.log

start() {
    echo "start"
    nohup $PROG -c $CFG >>$LOGS 2>&1 &
}

stop() {
    pkill -f $PROG
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 2
esac
